## NumPy Introduction

In [4]:
import numpy as np

In [5]:
list = [1,2,3]
print(list)

[1, 2, 3]


In [6]:
# Creating a numpy array from a python list
arr = np.array(list)
print(arr)

[1 2 3]


In [7]:
mat = [[1,2,3], [4,5,6], [7,8,9]]
print(mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [8]:
# Creating a numpy array from a python multidimensional list
mat_numpy = np.array(mat)
print(mat_numpy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Checking the size of an array (list or array)
print(len(list)) 

3


In [12]:
# Number of rows and columns in the array (python)
print(len(mat)) # rows 
print(len(mat[0])) # columns

3
3


In [15]:
# Numpy style
print(arr.shape) # lenght 3
print(mat_numpy.shape) # shape 3x3

(3,)
(3, 3)


In [16]:
# Number of dimensions
print(arr.ndim) # 1 dimension
print(mat_numpy.ndim) # 2 dimensions

1
2


In [18]:
# Range (python)
range(0,10)

range(0, 10)

In [17]:
# Range (numpy)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# Creating an array of zeros
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
# Creating an array of ones
np.ones((10,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
# Linspace (array whose numbers are within a evenly spaced range)
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [30]:
# Array of random numbers (between 0 and 1)
np.random.rand(4,4)

array([[0.53289514, 0.00212889, 0.53565612, 0.81498475],
       [0.46688892, 0.68668841, 0.52492899, 0.84204321],
       [0.78308156, 0.28788402, 0.32736469, 0.97067827],
       [0.40623832, 0.71396222, 0.86040975, 0.45997995]])

In [33]:
# Randn: cria números aleatórios, mas seguindo uma distruibuição normal (gaussiana)
# Parâmetros:
# Média = 0
# Variância = 1
np.random.randn(4,4)

array([[ 1.20443083,  0.41799559,  0.31634449, -0.91107762],
       [ 0.55053457,  0.80437278,  0.58558695, -1.67485665],
       [ 0.44656905,  0.55782582,  1.92677826, -0.55204287],
       [-1.05569138, -0.85593694,  0.54251182, -1.25450165]])

In [38]:
# Randint: cria números inteiros aletórios
vetor = np.random.randint(20,50,100)
print(vetor)

[23 20 38 35 25 25 44 46 35 30 32 37 38 47 49 21 21 39 42 30 36 31 29 40
 37 32 23 35 45 46 48 43 34 34 31 28 22 45 22 27 48 21 32 45 47 39 42 23
 47 37 41 24 47 43 48 39 48 46 20 46 41 43 29 27 26 31 49 38 31 21 37 48
 44 37 37 32 34 33 44 48 45 22 43 45 48 32 38 41 27 27 39 21 34 24 35 36
 37 40 43 20]


In [40]:
# Cálculos estatísticos
# Numpy: otimizado para cálculos (inclusive estatísticos)

49

In [42]:
# Máximo
print(vetor.max())

49


In [45]:
# Mínimo
print(vetor.min())

20


In [47]:
# Índice do máximo (se houver repetição, pega o primeiro)
print(vetor.argmax())

14


In [49]:
# Índice do mínimo
print(vetor.argmin())

1


In [51]:
# Média
print(vetor.mean())

35.75


In [55]:
# Desvio padrão (std = standard deviation)
print(vetor.std())

8.768551761836159


In [57]:
# Variância
print(vetor.var())

76.8875


In [59]:
# Mediana (ordena os dados para o cálculo correto)
print(np.median(vetor))

37.0


In [60]:
# Moda, apenas disponível no scipy
from scipy import stats
print(stats.mode(vetor))

ModeResult(mode=array([37]), count=array([7]))


In [62]:
## Indexação
print(vetor[10])

32


In [64]:
# Obtendo dados até a posição 10
print(vetor[:10])

[23 20 38 35 25 25 44 46 35 30]


In [66]:
# Obtendo dados até a posição 10, de 2 em 2
print(vetor[:10:2])

[23 38 25 44 35]


In [69]:
# Operações
arr_a = np.arange(1,10)
arr_b = np.arange(50,59)
print(arr_a, arr_b)

[1 2 3 4 5 6 7 8 9] [50 51 52 53 54 55 56 57 58]


In [71]:
print(arr_a + arr_b)

[51 53 55 57 59 61 63 65 67]


In [73]:
print(arr_a - arr_b)

[-49 -49 -49 -49 -49 -49 -49 -49 -49]


In [75]:
print(arr_a * arr_b)

[ 50 102 156 212 270 330 392 456 522]


In [76]:
print(arr_a / arr_b)

[0.02       0.03921569 0.05769231 0.0754717  0.09259259 0.10909091
 0.125      0.14035088 0.15517241]


In [77]:
print(arr_a + 10)

[11 12 13 14 15 16 17 18 19]


In [78]:
print(arr_a ** 2)

[ 1  4  9 16 25 36 49 64 81]


In [79]:
# Operação de conjuntos

In [83]:
# União (todos os valores que estão em A ou B, sem repetição)
print(np.union1d(arr_a, arr_b))

[ 1  2  3  4  5  6  7  8  9 50 51 52 53 54 55 56 57 58]


In [84]:
# Interseção
print(np.intersect1d(arr_a, arr_b))

array([], dtype=int64)

In [85]:
# Valores únicos
print(np.unique(arr_a))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
# Diferença entre conjuntos (A | B = itens em A e remover o que há de comum em B (interseção))
print(np.setdiff1d(arr_a, arr_b))

[1 2 3 4 5 6 7 8 9]


In [3]:
# Cópia e referência
arr_1 = np.arange(0,10)
arr_2 = arr_1[5:]
#arr_2 = arr_1[5:].copy() caso seja necessário manipular uma cópia
print(arr_1, arr_2)
print('______')
arr_2 += 5
print(arr_1, arr_2)

[0 1 2 3 4 5 6 7 8 9] [5 6 7 8 9]
______
[ 0  1  2  3  4 10 11 12 13 14] [10 11 12 13 14]
