## NumPy Introduction

In [97]:
import numpy as np

In [98]:
list = [1,2,3]
print(list)

[1, 2, 3]


In [99]:
# Creating a numpy array from a python list
arr = np.array(list)
print(arr)

[1 2 3]


In [100]:
mat = [[1,2,3], [4,5,6], [7,8,9]]
print(mat)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [101]:
# Creating a numpy array from a python multidimensional list
mat_numpy = np.array(mat)
print(mat_numpy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [102]:
# Checking the size of an array (list or array)
print(len(list)) 

3


In [103]:
# Number of rows and columns in the array (python)
print(len(mat)) # rows 
print(len(mat[0])) # columns

3
3


In [104]:
# Numpy style
print(arr.shape) # lenght 3
print(mat_numpy.shape) # shape 3x3

(3,)
(3, 3)


In [105]:
# Number of dimensions
print(arr.ndim) # 1 dimension
print(mat_numpy.ndim) # 2 dimensions

1
2


In [106]:
# Range (python)
print(range(0,10))

range(0, 10)


In [107]:
# Range (numpy)
print(np.arange(0,10))

[0 1 2 3 4 5 6 7 8 9]


In [108]:
# Creating an array of zeros
print(np.zeros((10,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [109]:
# Creating an array of ones
print(np.ones((10,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [110]:
# Linspace (array whose numbers are within a evenly spaced range)
print(np.linspace(0,5,10))

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [111]:
# Array of random numbers (between 0 and 1)
print(np.random.rand(4,4))

[[0.95331684 0.37835357 0.54242811 0.14929452]
 [0.00541013 0.41917043 0.99887179 0.62353905]
 [0.09238607 0.35703433 0.3471556  0.55102298]
 [0.64371821 0.31089226 0.95173118 0.52564261]]


In [112]:
# Randn: Creates an array of random numbers, following a Gaussian (normal) distribution
# Parameters:
# Average = 0
# Variance = 1
print(np.random.randn(4,4))

[[ 1.0492897   0.66967046  1.25851725 -0.78308   ]
 [-0.22467763 -0.56585128  0.03734924  0.87426296]
 [-1.67169467 -0.20335997 -0.28983117  1.59540519]
 [-0.48896328  0.65195933 -0.72549588  1.30550133]]


In [113]:
# Randint: Creates an array of random integers
array = np.random.randint(20,50,100)
print(array)

[34 24 39 21 21 45 27 38 29 32 41 27 47 38 34 30 43 25 20 46 30 40 37 28
 26 24 44 27 30 26 46 48 42 36 23 28 29 45 24 32 36 42 37 29 39 38 28 45
 22 24 24 37 29 34 45 42 46 33 37 41 34 44 38 32 35 27 42 39 24 44 32 32
 21 20 25 27 39 42 22 30 46 27 48 25 29 44 27 21 24 39 26 44 47 31 33 49
 40 39 42 29]


### Statistical calculations

In [114]:
# Maximum
print(array.max())

49


In [115]:
# Minimum
print(array.min())

20


In [116]:
# Maximum value index (if there is repetition, shows the first one)
print(array.argmax())

95


In [117]:
# Minimum value index 
print(array.argmin())

18


In [118]:
# Mean
print(array.mean())

33.93


In [119]:
# Standard deviation
print(array.std())

8.195431654281549


In [120]:
# Variance
print(array.var())

67.1651


In [121]:
# Median (sorts the data for correct calcs)
print(np.median(array))

33.5


In [122]:
# Mode (available in scipy)
from scipy import stats
print(stats.mode(array))

ModeResult(mode=array([24]), count=array([7]))


In [123]:
## Indexing
print(array[10])

41


In [124]:
# Getting data up to 10th position
print(array[:10])

[34 24 39 21 21 45 27 38 29 32]


In [125]:
# Getting data up to 10th position, 2 by 2
print(array[:10:2])

[34 39 21 27 29]


In [126]:
# Operations
arr_a = np.arange(1,10)
arr_b = np.arange(50,59)
print(arr_a, arr_b)

[1 2 3 4 5 6 7 8 9] [50 51 52 53 54 55 56 57 58]


In [127]:
# Array sum
print(arr_a + arr_b)

[51 53 55 57 59 61 63 65 67]


In [128]:
# Array subtraction
print(arr_a - arr_b)

[-49 -49 -49 -49 -49 -49 -49 -49 -49]


In [129]:
# Array multiplication
print(arr_a * arr_b)

[ 50 102 156 212 270 330 392 456 522]


In [130]:
# Array division
print(arr_a / arr_b)

[0.02       0.03921569 0.05769231 0.0754717  0.09259259 0.10909091
 0.125      0.14035088 0.15517241]


In [131]:
# Array sum (to each element)
print(arr_a + 10)

[11 12 13 14 15 16 17 18 19]


In [132]:
# Array multiplication (to each element)
print(arr_a ** 2)

[ 1  4  9 16 25 36 49 64 81]


In [133]:
# Sets operations

In [134]:
# Union (all values that are in A or B, without repetition)
print(np.union1d(arr_a, arr_b))

[ 1  2  3  4  5  6  7  8  9 50 51 52 53 54 55 56 57 58]


In [135]:
# Intersection
print(np.intersect1d(arr_a, arr_b))

[]


In [136]:
# Unique values
print(np.unique(arr_a))

[1 2 3 4 5 6 7 8 9]


In [137]:
# Difference between sets (A | B = items in A and removal what is common in B (intersection))
print(np.setdiff1d(arr_a, arr_b))

[1 2 3 4 5 6 7 8 9]


In [138]:
# Copy and reference
arr_1 = np.arange(0,10)
arr_2 = arr_1[5:]
# arr_2 = arr_1[5:].copy() if necessary to manipulate a copy
print(arr_1, arr_2)
print('______')
arr_2 += 5
print(arr_1, arr_2)

[0 1 2 3 4 5 6 7 8 9] [5 6 7 8 9]
______
[ 0  1  2  3  4 10 11 12 13 14] [10 11 12 13 14]
