## Exercises list 01

In [18]:
import numpy as np

In [19]:
# Create an array with 10 '0's
print(np.zeros((10)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
# Create an array with 10 '1's
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [21]:
# Create an array with 10 '5's
print(np.full(10, 5))

[5 5 5 5 5 5 5 5 5 5]


In [22]:
# Create an array with integers between 15 and 150
print(np.random.randint(15,150,10))

[ 45  45  86 107  88  78  83 139 124  51]


In [23]:
# Create an array with all odd numbers between 10 and 50
arr = np.arange(10,51,1)
odd_arr = arr[arr % 2==1]
print(odd_arr)

[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


In [24]:
# Create a 3 x 3 array whose numbers follow a Gaussian distribution
## Also calculate the sum of each column, maximum, minimum, average, standard deviation and variance

arr = np.random.randn(3,3)
print('Array: \n', arr, '\n')
print('Maximum \n', arr.max())
print('Minimum: \n', arr.min())
print('Mean: \n', arr.mean())
print('Variance: \n', arr.var())
print('Standard deviation: \n', arr.std())
print('Columns sum: \n', arr.sum(0))

Array: 
 [[-1.07649416  1.07850604 -0.19641523]
 [-0.60938175 -0.40642045 -0.99357094]
 [ 0.38004503  0.46783308  2.57482337]] 

Maximum 
 2.5748233703055776
Minimum: 
 -1.0764941606942593
Mean: 
 0.135436111042123
Variance: 
 1.1902479716052552
Standard deviation: 
 1.0909848631421315
Columns sum: 
 [-1.30583087  1.13991867  1.38483721]


In [ ]:
# Create a 2d array with '1.0' on the edges and '0.0' on the internal values
rows = int(input("Rows: \n"))
columns = int(input("Columns: \n"))
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
print("Result: \n", arr)